# this is testing file

[general]
raster_num_closest_points = 10
dates = ["2022_06_15", "2022_07_11", "2022_07_20"]
treatments = ["eko"]
varieties = [
	"Carolus",
	"Alouette",
	"Twister",
	"Otolia",
	"KIS_Tamar",
	"KIS_Blegos",
	"KIS_Kokra",
	"Levante",
]

[multispectral]
channels = ["blue", "green", "red", "red_edge", "nir"]
location_type = "measured"

[sampler]
splitter = "StratifyAllSplitter"
split_size_val = 0.0
split_size_test = 0.25
shuffle = true
random_state = 1
stratify = true

[features_generator]
features_engineer = "AutoFeatClassifier"
feateng_steps = 2
verbose = 1

[formatter]
formatter = "ClassificationFormatter"
classification_labels = ["varieties"]

[model]
pipeline = ["XGBClassifier"]

[optimizer]
n_trials = 200
n_jobs = 10
scoring_metric = "f1_weighted"
scoring_mode = "maximize"

[optimizer.tuned_parameters]

[optimizer.tuned_parameters.optimize_int]
XGBClassifier__n_estimators = [100, 1000]
XGBClassifier__max_depth = [3, 10]

[optimizer.tuned_parameters.optimize_float]
XGBClassifier__learning_rate = [0.001, 0.1]
XGBClassifier__min_child_weight = [1.0, 10.0]
XGBClassifier__gamma = [0.001, 1.0]
XGBClassifier__subsample = [0.5, 1.0]
XGBClassifier__colsample_bytree = [0.5, 1.0]
XGBClassifier__reg_alpha = [0.001, 1.0]
XGBClassifier__reg_lambda = [0.001, 1.0]

[optimizer.validator]
validator = "RepeatedStratifiedKFold"
n_splits = 5
n_repeats = 3
random_state = 1

[registry]
model_name = "Feat_XGBClassifier"
description = "Differentiation between eko and konv treatments"
metadata = ["test_size=0.25", "n_splits=5", "n_repeats=3", "random_state=1"]

[evaluator]
logger = "ArtifactLoggerClassification"
