[general]
treatments = ["eko", "konv"]

[features_generator]
features_engineer = "AutoSpectralIndicesPlusGeneratedClassification"
feateng_steps = 2

[formatter]
stratify_by_meta = true

[registry]
model_name = "07ek_clf"
