[general]
treatments = ["eko", "konv"]
varieties = ["Alouette", "Carolus", "Otolia", "KIS_Tamar", "KIS_Blegos"]

[features_generator]
features_engineer = "AutoSpectralIndicesPlusGeneratedClassification"
feateng_steps = 2

[formatter]
stratify_by_meta = true

[registry]
model_name = "04ek_clf"
