[general]
treatments = ["eko", "konv"]

[features_generator]
features_engineer = "AutoSpectralIndicesPlusGeneratedRegression"
feateng_steps = 2

[formatter]
regression_label = "LICOR_ETR"
average_duplicates = true

[registry]
model_name = "ETR_reg"
