# this is testing file

[general]
raster_num_closest_points = 10
dates = ["2022_07_20"]
treatments = ["eko"]
varieties = [
	"Carolus",
	"Alouette",
	"Twister",
	"Otolia",
	"KIS_Tamar",
	"KIS_Blegos",
	"KIS_Kokra",
	"Levante",
]

[multispectral]
channels = ["blue", "green", "red", "red_edge", "nir"]
location_type = "measured"

[sampler]
splitter = "StratifyAllSplitter"
split_size_val = 0.0
split_size_test = 0.25
shuffle = true
random_state = 1
stratify = false

[features_generator]
features_engineer = "AutoFeatRegressor"
feateng_steps = 2
verbose = 2
n_jobs = -1

[formatter]
formatter = "RegressionFormatter"
regression_label = "Alternaria"

[model]
pipeline = ["XGBRegressor"]

[optimizer]
n_trials = 100
n_jobs = 10
scoring_metric = "neg_root_mean_squared_error"
scoring_mode = "maximize"

[optimizer.tuned_parameters]

[optimizer.tuned_parameters.optimize_int]
XGBRegressor__n_estimators = [100, 1000]
XGBRegressor__max_depth = [3, 10]

[optimizer.tuned_parameters.optimize_float]
XGBRegressor__learning_rate = [0.001, 0.1]
XGBRegressor__min_child_weight = [1.0, 10.0]
XGBRegressor__gamma = [0.001, 1.0]
XGBRegressor__subsample = [0.5, 1.0]
XGBRegressor__colsample_bytree = [0.5, 1.0]
XGBRegressor__reg_alpha = [0.001, 1.0]
XGBRegressor__reg_lambda = [0.001, 1.0]

[optimizer.validator]
validator = "RepeatedKFold"
n_splits = 5
n_repeats = 3
random_state = 1

[registry]
model_name = "Feat_XGBRegressor"
description = "Regression"
metadata = ["test_size=0.25", "n_splits=5", "n_repeats=3", "random_state=1"]

[evaluator]
logger = "ArtifactLoggerRegression"
