[general]
treatments = ["eko", "konv"]

[features_generator]
features_engineer = "AutoSpectralIndicesPlusGeneratedRegression"
feateng_steps = 2

[formatter]
regression_label = "SPAD"
average_duplicates = true

[registry]
model_name = "SPAD_reg"
