# this is testing file

["general"]
num_closest_points = 10

["multispectral"]
dates = ["2022_06_15"]
treatments = ["eko", "konv"]
channels = ["blue", "green"]
location_type = "measured"

["sampler"]
splitter = "StratifySplitter"
shuffle = true
random_state = 1
split_size_val = 0.3
split_size_test = 0.3

["formatter"]
formatter = "ClassificationFormatter"
Labels_to_encode = ["varieties", "treatments"]
