# this is testing file

["general"]
num_closest_points = 10

["multispectral"]
dates = ["2022_06_15"]
treatments = ["eko", "konv"]
channels = ["blue"]
location_type = "measured"

["sampler"]
splitter = "SimpleSplitter"
split_size_val = 0.3
split_size_test = 0.3
shuffle = true
random_state = 1
stratify = true

["formatter"]
formatter = "ClassificationFormatter"
Labels_to_encode = ["treatments"]
