# this is testing file

[general]
raster_num_closest_points = 10
dates = ["2022_07_11"]
treatments = ["eko"]

[multispectral]
channels = ["blue", "green", "nir", "red_edge", "red"]
location_type = "measured"

[sampler]
splitter = "SimpleSplitter"
split_size_val = 0.0
split_size_test = 0.3
shuffle = true
random_state = 1
stratify = false

[formatter]
formatter = "RegressionFormatter"
regression_label = "SPAD"

[model]
pipeline = ["AutoFeatRegressor", "RandomForestRegressor"]

[optimizer]
n_trials = 1
n_jobs = 10
scoring_metric = "neg_root_mean_squared_error"
scoring_mode = "maximize"

[optimizer.tuned_parameters]
[optimizer.tuned_parameters.optimize_int]
RandomForestRegressor__n_estimators = [100, 1000]
RandomForestRegressor__max_depth = [5, 50]
RandomForestRegressor__min_samples_split = [2, 10]
RandomForestRegressor__min_samples_leaf = [1, 10]
[optimizer.tuned_parameters.optimize_category]
RandomForestRegressor__max_features = ["sqrt", "log2"]
AutoFeatRegressor__feateng_steps = [2]
AutoFeatRegressor__verbose = [0]

[optimizer.validator]
validator = "RepeatedKFold"
n_splits = 5
n_repeats = 3
random_state = 1

[registry]
model_name = "TestModelReg"
description = "Regression"
metadata = ["test_size=0.3", "n_splits=5", "n_repeats=3", "random_state=1"]

[evaluator]
logger = "ArtifactLoggerRegression"
