# this is testing file

[general]
raster_num_closest_points = 10
dates = ["2022_07_20"]
treatments = ["eko"]

[multispectral]
channels = ["blue", "green", "nir", "red_edge", "red"]
location_type = "measured"

[sampler]
splitter = "SimpleSplitter"
split_size_val = 0.0
split_size_test = 0.3
shuffle = true
random_state = 1
stratify = true

[formatter]
formatter = "RegressionFormatter"
regression_label = "SPAD"

[model]
pipeline = ["XGBClassifier"]

[optimizer]
n_trials = 3
n_jobs = 10
scoring_metric = "f1_weighted"
scoring_mode = "maximize"

[optimizer.tuned_parameters]
# [optimizer.tuned_parameters.optimize_float]
# SVC__C = [0.01, 1.0]
# SVC__gamma = [1e-5, 1.0]
# [optimizer.tuned_parameters.optimize_category]
# SVC__kernel = ["rbf"]

[optimizer.validator]
validator = "RepeatedStratifiedKFold"
n_splits = 3
n_repeats = 3
random_state = 1

[registry]
model_name = "TestModel"
description = "Differentiation between eko and konv treatments"
metadata = ["test_size=0.3", "n_splits=5", "n_repeats=3", "random_state=1"]

[evaluator]
logger = "ArtifactLoggerClassification"
