# this is testing file

[general]
num_closest_points = 10

[multispectral]
dates = ["2022_06_15"]
treatments = ["eko", "konv"]
channels = ["blue"]
location_type = "measured"

[sampler]
splitter = "SimpleSplitter"
split_size_val = 0.0
split_size_test = 0.3
shuffle = true
random_state = 1
stratify = true

[formatter]
formatter = "ClassificationFormatter"
labels_to_encode = ["treatments"]

[model]
pipeline = ["SVC"]

[optimizer]
n_trials = 10
timeout = 1000
n_jobs = 1
scoring_metric = "f1"
scoring_mode = "maximize"

[optimizer.tuned_parameters]
[optimizer.tuned_parameters.optimize_int]
SVC__C = [1, 10]
SVC__degree = [1, 3]
[optimizer.tuned_parameters.optimize_float]
SVC__gamma = [0.001, 0.1]
[optimizer.tuned_parameters.optimize_category]
SVC__kernel = ["rbf", "poly", "sigmoid"]

[optimizer.validator]
validator = "RepeatedStratifiedKFold"
n_splits = 5
n_repeats = 3
random_state = 1

[evaluator]
logger = "ArtifactLoggerClassification"
